[package]
name = "tokencount"
version = "0.1.0-alpha.1"
edition = "2024"

[dependencies]
glob = "0.3.2"
clap = { version = "4.5.40", features = ["derive"] }
tokenizers = { version = "0.21.2", features = ["http"] }
